LIST_VIEW = {"get": "list"}
CREATE_VIEW = {"post": "create"}

RETRIEVE_VIEW = {"get": "retrieve"}
UPDATE_VIEW = {"put": "update"}
PARTIAL_UPDATE_VIEW = {"patch": "partial_update"}
DESTROY_VIEW = {"delete": "destroy"}

STANDARD_VIEW = {**LIST_VIEW, **CREATE_VIEW}
STANDARD_DETAIL_VIEW = {
    **RETRIEVE_VIEW,
    **UPDATE_VIEW,
    **PARTIAL_UPDATE_VIEW,
    **DESTROY_VIEW,
}

RETRIEVE_UPDATE_VIEW = {**RETRIEVE_VIEW, **UPDATE_VIEW, **PARTIAL_UPDATE_VIEW}
RETRIEVE_DESTROY_VIEW = {**RETRIEVE_VIEW, **DESTROY_VIEW}
UPDATE_DESTROY_VIEW = {**UPDATE_VIEW, **DESTROY_VIEW}
